language: cpp
branches:
  only:
    - master
    - devel
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  # this is going to break on osx, use a shell script?
  - sudo apt-get update -qq
  - sudo apt-get install -qq make
  - sudo apt-get install -qq gcc-multilib g++-multilib
  - sudo apt-get install -qq libuuid1 uuid-dev
script:
  - ./configure
  - make all
rvm:
  - 1.9.3
env:
  global:
    - FOUNDATION_CONFIG_PARANOID=yes
  matrix:
    - FOUNDATION_CONFIG_CONFIGURATION=debug FOUNDATION_CONFIG_LINKAGE=static FOUNDATION_CONFIG_ARCHITECTURE=x86
    - FOUNDATION_CONFIG_CONFIGURATION=development FOUNDATION_CONFIG_LINKAGE=static FOUNDATION_CONFIG_ARCHITECTURE=x86
    - FOUNDATION_CONFIG_CONFIGURATION=release FOUNDATION_CONFIG_LINKAGE=static FOUNDATION_CONFIG_ARCHITECTURE=x86
    - FOUNDATION_CONFIG_CONFIGURATION=debug FOUNDATION_CONFIG_LINKAGE=dynamic FOUNDATION_CONFIG_ARCHITECTURE=x86
    - FOUNDATION_CONFIG_CONFIGURATION=development FOUNDATION_CONFIG_LINKAGE=dynamic FOUNDATION_CONFIG_ARCHITECTURE=x86
    - FOUNDATION_CONFIG_CONFIGURATION=release FOUNDATION_CONFIG_LINKAGE=dynamic FOUNDATION_CONFIG_ARCHITECTURE=x86
    - FOUNDATION_CONFIG_CONFIGURATION=debug FOUNDATION_CONFIG_LINKAGE=static FOUNDATION_CONFIG_ARCHITECTURE=x86-64
    - FOUNDATION_CONFIG_CONFIGURATION=development FOUNDATION_CONFIG_LINKAGE=static FOUNDATION_CONFIG_ARCHITECTURE=x86-64
    - FOUNDATION_CONFIG_CONFIGURATION=release FOUNDATION_CONFIG_LINKAGE=static FOUNDATION_CONFIG_ARCHITECTURE=x86-64
    - FOUNDATION_CONFIG_CONFIGURATION=debug FOUNDATION_CONFIG_LINKAGE=dynamic FOUNDATION_CONFIG_ARCHITECTURE=x86-64
    - FOUNDATION_CONFIG_CONFIGURATION=development FOUNDATION_CONFIG_LINKAGE=dynamic FOUNDATION_CONFIG_ARCHITECTURE=x86-64
    - FOUNDATION_CONFIG_CONFIGURATION=release FOUNDATION_CONFIG_LINKAGE=dynamic FOUNDATION_CONFIG_ARCHITECTURE=x86-64
  allow_failures:
    - os: osx
cache:
  - apt
notifications:
  email:
    recipients:
      - developers@bitbyte.ca
    on_success: change
    on_failure: always
